[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "iaps"
authors = [{name = "Jon Björn Mårtensson", email = "jon.m@live.se"}]
dynamic = ["version", "description"]
